# Generated by Django 3.2.6 on 2021-08-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager')], max_length=120),
        ),
    ]
